url: "https://www.schuylines.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "schuylines" # the name of your site, e.g. ACME Corp.
logo: "/assets/images/canvas6.png"

author: Schuy H
alias: Sky # author's alias -- appears in body of mailto: link
email: schuy+net@schuylines.net # PUBLICALLY AVAILABLE in "contact us" mailto: link

sass:
  style: compressed